<?php

namespace Overlook\Foundation\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Overlook\Foundation\Review\WidgetMarkup;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * Puts the review widget on the page.
 *
 * Injected into the response rather than offered as a Blade component the
 * layout includes, because there is no layout this package can rely on. Sites
 * are generated by whatever the Laravel installer ships that day, across five
 * starter kits, and the studio never edits the result — so a tag that has to be
 * placed by hand reaches the next project and none of the forty already built.
 * That is the same drift the template this package replaced died of.
 *
 * The cost is honest: a developer reading the layout sees nothing that explains
 * the script. It is the lesser cost, since there is no studio-owned layout for
 * them to read in the first place.
 */
class InjectReviewWidget
{
    public function handle(Request $request, Closure $next): Response
    {
        $response = $next($request);

        /**
         * A live site never carries the widget, and this is the last place that
         * can be true regardless of what the environment says.
         *
         * The studio's provisioner withholds both variables from a production
         * environment and refuses the switch that would connect one, so
         * reaching here with a key set means somebody typed one into a
         * dashboard by hand. That is exactly the case worth catching: the
         * widget is a launcher in the corner of every page, addressed to
         * whoever is looking, and the people looking at a live site are the
         * client's own visitors.
         */
        if (app()->environment('production')) {
            return $response;
        }

        $key = config('foundation.review.key');
        $source = config('foundation.review.url');

        /**
         * The ordinary case on every production site: nothing to inject. Both
         * are required — a tag with an address and no key reports nowhere, and
         * a tag with a key and no address does not load at all.
         */
        if (! config('foundation.review.enabled')
            || ! is_string($key) || $key === ''
            || ! is_string($source) || $source === '') {
            return $response;
        }

        /** Neither holds a body this can rewrite without buffering the whole thing. */
        if ($response instanceof StreamedResponse || $response instanceof BinaryFileResponse) {
            return $response;
        }

        if (! str_contains((string) $response->headers->get('Content-Type'), 'text/html')) {
            return $response;
        }

        $content = $response->getContent();

        if (! is_string($content)) {
            return $response;
        }

        /**
         * The last closing body tag, not the first. A page that shows escaped
         * markup — a docs page, a mail preview, anything rendering a snippet —
         * contains an earlier one that is not the end of the document, and
         * str_replace would put the widget inside it.
         */
        $position = strripos($content, '</body>');

        if ($position === false) {
            return $response;
        }

        $content = substr($content, 0, $position).WidgetMarkup::for($key, $source).substr($content, $position);

        /**
         * What the response was rendered from, which setContent overwrites with
         * the string it is given. Nothing serving the page cares, but every
         * assertion about it does: assertViewIs, assertViewHas and Inertia's
         * assertInertia all read the view back off the response, and against a
         * string they report the page is not a view at all. Left alone, this
         * middleware fails the test suite of every application it is installed
         * in — for a difference the browser never sees.
         */
        $original = $response->original;

        $response->setContent($content);

        $response->original = $original;

        /**
         * setContent leaves any Content-Length the response already declared,
         * which is now short by exactly the widget — and a browser handed a
         * truncated document renders a blank page.
         */
        if ($response->headers->has('Content-Length')) {
            $response->headers->set('Content-Length', (string) strlen($content));
        }

        return $response;
    }
}
